source 'https://github.com/CocoaPods/Specs.git'

target 'DVITutorialView', :exclusive => true do
  pod "DVITutorialView", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "DVITutorialView", :path => "../"

  
end
